Repository ShayanMahnam/lentegeur-hospital-facility-board, pull requests merged in 2023-06, with the labels that each got.

#14 13 - Allow the use of JSX across the Project
  client/src/App.jsx
  client/src/index.jsx
  client/src/pages/About.jsx
  client/src/pages/Home.jsx
  client/webpack/common.config.js
Labels: bug, enhancement

#15 11 - Setup Initial File and Folder Structure - bazmurphy
  client/src/App.jsx
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/components.md
  client/src/index.html
  client/src/index.jsx
  client/src/layouts/RootLayout/RootLayout.css
  client/src/layouts/RootLayout/RootLayout.jsx
  client/src/layouts/layouts.md
  client/src/pages/AboutPage/AboutPage.css
  client/src/pages/AboutPage/AboutPage.jsx
  client/src/pages/AboutPage/components/components.md
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContactUsPage/ContactUsPage.jsx
  client/src/pages/ContactUsPage/components/components.md
  client/src/pages/EventsPage/EventsPage.css
  client/src/pages/EventsPage/EventsPage.jsx
  client/src/pages/EventsPage/components/components.md
  client/src/pages/GalleryPage/GalleryPage.css
  client/src/pages/GalleryPage/GalleryPage.jsx
  client/src/pages/GalleryPage/components/components.md
  client/src/pages/GetInvolvedPage/GetInvolvedPage.css
  client/src/pages/GetInvolvedPage/GetInvolvedPage.jsx
  client/src/pages/GetInvolvedPage/components/components.md
  client/src/pages/HomePage/HomePage.css
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/components.md
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/NewsPage/NewsPage.jsx
  client/src/pages/NewsPage/components/components.md
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/pages/ServicesPage/ServicesPage.jsx
  client/src/pages/ServicesPage/components/components.md
  client/src/pages/_backup/About.jsx
  client/src/pages/_backup/Home.css
  client/src/pages/_backup/Home.jsx
  client/src/pages/_backup/_backup.md
  client/src/pages/_backup/logo.svg
  client/src/utils/utils.md
Labels: enhancement

#28 27 - Allow Prettier to autoformat locally - Baz
  .vscode/settings.json
Labels: bug

#30 25 - Create Global Styles - Shayan, Vitalina, Khadija, Baz
  client/src/components/Line/Line.css
  client/src/components/Line/Line.jsx
  client/src/layouts/RootLayout/RootLayout.css
  client/src/layouts/RootLayout/RootLayout.jsx
  client/src/styles/globals.css
Labels: enhancement

#21 1 - About Page - Vitalina
  client/src/assets/grey_circle_image.svg
  client/src/assets/grey_image.svg
  client/src/pages/AboutPage/AboutPage.css
  client/src/pages/AboutPage/AboutPage.jsx
  client/src/pages/AboutPage/components/Affiliate/Affiliate.css
  client/src/pages/AboutPage/components/Affiliate/Affiliate.jsx
  client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.css
  client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.jsx
  client/src/pages/AboutPage/components/HistorySection/HistorySection.css
  client/src/pages/AboutPage/components/HistorySection/HistorySection.jsx
  client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.css
  client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
Labels: enhancement

#23 6 - Contact Us Page - Baz
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContactUsPage/ContactUsPage.jsx
  client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.css
  client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
  client/src/pages/ContactUsPage/components/ContactUsSection/ContactUsSection.css
  client/src/pages/ContactUsPage/components/ContactUsSection/ContactUsSection.jsx
  client/src/pages/ContactUsPage/components/VisitUsMap/VisitUsMap.css
  client/src/pages/ContactUsPage/components/VisitUsMap/VisitUsMap.jsx
  client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.css
  client/src/pages/ContactUsPage/components/VisitUsSection/VisitUsSection.jsx
  client/src/styles/globals.css
  package-lock.json
  package.json
Labels: enhancement

#24 2 - News Page & Events Page - Shayan
  client/src/components/ContentBox/ContentBox.css
  client/src/components/ContentBox/ContentBox.jsx
  client/src/pages/EventsPage/EventsPage.css
  client/src/pages/EventsPage/EventsPage.jsx
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/NewsPage/NewsPage.jsx
Labels: enhancement

#16 10 - Footer Component - Khadija
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
Labels: enhancement
