Repository ShayanMahnam/lentegeur-hospital-facility-board, pull requests merged in 2023-07, with the labels that each got.

#31 3 - Header component - Oleh and Vitalina
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  package-lock.json
  package.json
Labels: enhancement

#64 63 - Fix Netlify Routing Redirect - Baz
  client/public/_redirects
Labels: bug

#69 68 - Prettier & Eslint Configuration For Client - Baz
  client/.eslintrc.json
  client/.prettierrc.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/ContentBox/ContentBox.css
  client/src/main.jsx
  client/src/pages/AboutPage/components/components.md
  client/src/pages/ContactUsPage/components/components.md
  client/src/pages/EventsPage/components/components.md
  client/src/pages/GalleryPage/components/components.md
  client/src/pages/GetInvolvedPage/components/components.md
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/components.md
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/NewsPage/components/components.md
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/pages/ServicesPage/components/components.md
  client/src/utils/utils.md
Labels: bug, enhancement

#67 66-enhancement-for-news-and-events-card-shayan
  client/src/components/Card/Card.css
  client/src/components/Card/Card.jsx
  client/src/components/ContentBox/ContentBox.css
  client/src/components/ContentBox/ContentBox.jsx
  client/src/pages/EventsPage/EventsPage.css
  client/src/pages/EventsPage/EventsPage.jsx
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/NewsPage/NewsPage.jsx
Labels: enhancement

#32 29 - Home Page - Khadija
  client/package-lock.json
  client/package.json
  client/src/components/Card/Card.css
  client/src/pages/HomePage/HomePage.css
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/assets/slider01.jpg
  client/src/pages/HomePage/assets/slider02.jpg
  client/src/pages/HomePage/assets/slider03.jpg
  client/src/pages/HomePage/components/HomeCardList/HomeCardList.css
  client/src/pages/HomePage/components/HomeCardList/HomeCardList.jsx
  client/src/pages/HomePage/components/HomeGetInvolvedSection/HomeGetInvolvedSection.css
  client/src/pages/HomePage/components/HomeGetInvolvedSection/HomeGetInvolvedSection.jsx
  client/src/pages/HomePage/components/HomeHero/HomeHero.css
  client/src/pages/HomePage/components/HomeHero/HomeHero.jsx
  client/src/pages/HomePage/components/HomeHero/css-helpers/slick-theme.css
  client/src/pages/HomePage/components/HomeHero/css-helpers/slick.css
  client/src/styles/globals.css
Labels: enhancement

#75 71 - Fix Header - responsiveness -Vitalina
  client/src/components/Header/Header.css
Labels: bug

#74 73 - Remove margin-top from main - Vitalina
  client/src/pages/AboutPage/AboutPage.css
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/EventsPage/EventsPage.css
  client/src/pages/GalleryPage/GalleryPage.css
  client/src/pages/GetInvolvedPage/GetInvolvedPage.css
  client/src/pages/HomePage/HomePage.css
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/styles/globals.css
Labels: bug

#72 41 - Create Database Models - Baz
  server/src/api/event/content-types/event/schema.json
  server/src/api/event/controllers/event.js
  server/src/api/event/routes/event.js
  server/src/api/event/services/event.js
  server/src/api/gallery-album/content-types/gallery-album/schema.json
  server/src/api/gallery-album/controllers/gallery-album.js
  server/src/api/gallery-album/routes/gallery-album.js
  server/src/api/gallery-album/services/gallery-album.js
  server/src/api/news-article/content-types/news-article/schema.json
  server/src/api/news-article/controllers/news-article.js
  server/src/api/news-article/routes/news-article.js
  server/src/api/news-article/services/news-article.js
  server/src/api/service/content-types/service/schema.json
  server/src/api/service/controllers/service.js
  server/src/api/service/routes/service.js
  server/src/api/service/services/service.js
Labels: enhancement

#70 55 - investigate/create a dynamic page with dynamic routing - Vitalina
  client/src/App.jsx
  client/src/components/Card/Card.css
  client/src/components/Card/Card.jsx
  client/src/components/GoBackButton/GoBackButton.css
  client/src/components/GoBackButton/GoBackButton.jsx
  client/src/newsEventsData.json
  client/src/pages/ContentPage/ContentPage.css
  client/src/pages/ContentPage/ContentPage.jsx
  client/src/pages/EventsPage/EventsPage.jsx
  client/src/pages/NewsPage/NewsPage.jsx
  client/src/pages/ServicePage/ServicePage.css
  client/src/pages/ServicePage/ServicePage.jsx
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/pages/ServicesPage/ServicesPage.jsx
  client/src/pages/ServicesPage/components/Services/Services.css
  client/src/pages/ServicesPage/components/Services/Services.jsx
  client/src/servicesData.json
Labels: enhancement

#82 81 - Fixed Card component on all pages - Vitalina
  client/src/assets/grey_image.svg
  client/src/components/Card/Card.css
  client/src/components/Card/Card.jsx
  client/src/data/eventsData.json
  client/src/data/newsData.json
  client/src/data/servicesData.json
  client/src/pages/AboutPage/components/HistorySection/HistorySection.jsx
  client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
  client/src/pages/ContentPage/ContentPage.jsx
  client/src/pages/EventsPage/EventsPage.jsx
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/HomeCardList/HomeCardList.jsx
  client/src/pages/NewsPage/NewsPage.jsx
  client/src/pages/ServicePage/ServicePage.jsx
  client/src/pages/ServicesPage/ServicesPage.jsx
  client/src/pages/ServicesPage/components/Services/Services.css
Labels: bug

#77 76 - Gallery Iteration 2.0(?) - Baz
  client/src/App.jsx
  client/src/components/ErrorComponent/ErrorComponent.css
  client/src/components/ErrorComponent/ErrorComponent.jsx
  client/src/components/Loading/Loading.css
  client/src/components/Loading/Loading.jsx
  client/src/components/LoadingIcon/LoadingIcon.css
  client/src/components/LoadingIcon/LoadingIcon.jsx
  client/src/pages/GalleryAlbumPage/GalleryAlbumPage.css
  client/src/pages/GalleryAlbumPage/GalleryAlbumPage.jsx
  client/src/pages/GalleryPage/GalleryPage.css
  client/src/pages/GalleryPage/GalleryPage.jsx
  client/src/pages/GalleryPage/components/GalleryCard/GalleryCard.css
  client/src/pages/GalleryPage/components/GalleryCard/GalleryCard.jsx
  client/src/pages/NotFoundPage/NotFoundPage.css
  client/src/pages/NotFoundPage/NotFoundPage.jsx
Labels: enhancement

#80 79-added padding-bottom to service title-khadija
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/pages/ServicesPage/ServicesPage.jsx
Labels: bug, enhancement

#86 85 - Content Fetching - Baz
  client/package.json
  client/src/App.jsx
  client/src/components/Card/Card.css
  client/src/components/Card/Card.jsx
  client/src/components/ErrorComponent/ErrorComponent.jsx
  client/src/components/Header/Header.css
  client/src/components/Loading/Loading.css
  client/src/pages/AboutPage/AboutPage.css
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContentPage/ContentPage.css
  client/src/pages/ContentPage/ContentPage.jsx
  client/src/pages/EventsPage/EventsPage.css
  client/src/pages/EventsPage/EventsPage.jsx
  client/src/pages/GalleryAlbumPage/GalleryAlbumPage.css
  client/src/pages/GalleryAlbumPage/GalleryAlbumPage.jsx
  client/src/pages/GalleryPage/GalleryPage.css
  client/src/pages/GalleryPage/GalleryPage.jsx
  client/src/pages/GetInvolvedPage/GetInvolvedPage.css
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/HomeCardList/HomeCardList.jsx
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/NewsPage/NewsPage.jsx
  client/src/pages/NotFoundPage/NotFoundPage.css
  client/src/pages/ServicePage/ServicePage.css
  client/src/pages/ServicePage/ServicePage.jsx
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/pages/ServicesPage/ServicesPage.jsx
  client/src/pages/ServicesPage/components/ServiceCard/ServiceCard.css
  client/src/pages/ServicesPage/components/ServiceCard/ServiceCard.jsx
  client/src/pages/ServicesPage/components/Services/Services.jsx
  client/src/styles/globals.css
  client/src/utils/parseContent.js
Labels: enhancement

#98 97 - About Page Dynamic Content - Baz
  client/src/pages/AboutPage/AboutPage.jsx
  client/src/pages/AboutPage/components/Affiliate/Affiliate.css
  client/src/pages/AboutPage/components/Affiliate/Affiliate.jsx
  client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.css
  client/src/pages/AboutPage/components/GovernanceSection/GovernanceSection.jsx
  client/src/pages/AboutPage/components/HistorySection/HistorySection.css
  client/src/pages/AboutPage/components/HistorySection/HistorySection.jsx
  client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.css
  client/src/pages/AboutPage/components/NetworkingSection/NetworkingSection.jsx
  server/src/api/about-page/content-types/about-page/schema.json
  server/src/api/about-page/controllers/about-page.js
  server/src/api/about-page/routes/about-page.js
  server/src/api/about-page/services/about-page.js
Labels: enhancement

#96 91-latest-new-design-home-page-shayan
  client/package-lock.json
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.css
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.jsx
  client/src/pages/HomePage/components/HomeEventsSection/components/HomeEventCardLeft/HomeEventCardLeft.css
  client/src/pages/HomePage/components/HomeEventsSection/components/HomeEventCardLeft/HomeEventCardLeft.jsx
  client/src/pages/HomePage/components/HomeEventsSection/components/HomeEventCardRight/HomeEventCardRight.css
  client/src/pages/HomePage/components/HomeEventsSection/components/HomeEventCardRight/HomeEventCardRight.jsx
  client/src/pages/HomePage/components/HomeNewsSection/HomeNewsSection.css
  client/src/pages/HomePage/components/HomeNewsSection/HomeNewsSection.jsx
  client/src/pages/HomePage/components/HomeNewsSection/components/HomeNewsCard/HomeNewsCard.css
  client/src/pages/HomePage/components/HomeNewsSection/components/HomeNewsCard/HomeNewsCard.jsx
  client/src/pages/HomePage/components/backup/HomeCardList/HomeCardList.css
  client/src/pages/HomePage/components/backup/HomeCardList/HomeCardList.jsx
Labels: enhancement

#95 92 - Services & Get Involved Design Home Page - Baz
  client/public/logo.png
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/Line/Line.css
  client/src/components/Line/Line.jsx
  client/src/pages/HomePage/HomePage.css
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.css
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.jsx
  client/src/pages/HomePage/components/HomeEventsSection/components/HomeEventCardLeft/HomeEventCardLeft.css
  client/src/pages/HomePage/components/HomeEventsSection/components/HomeEventCardRight/HomeEventCardRight.css
  client/src/pages/HomePage/components/HomeGetInvolvedSection/HomeGetInvolvedSection.css
  client/src/pages/HomePage/components/HomeGetInvolvedSection/HomeGetInvolvedSection.jsx
  client/src/pages/HomePage/components/HomeNewsSection/HomeNewsSection.css
  client/src/pages/HomePage/components/HomeNewsSection/HomeNewsSection.jsx
  client/src/pages/HomePage/components/HomeServicesSection/HomeServicesSection.css
  client/src/pages/HomePage/components/HomeServicesSection/HomeServicesSection.jsx
  client/src/pages/HomePage/components/HomeServicesSection/components/HomeServiceCard/HomeServiceCard.css
  client/src/pages/HomePage/components/HomeServicesSection/components/HomeServiceCard/HomeServiceCard.jsx
  client/src/pages/HomePage/components/backup/HomeGetInvolvedSection/HomeGetInvolvedSection.css
  client/src/pages/HomePage/components/backup/HomeGetInvolvedSection/HomeGetInvolvedSection.jsx
  client/src/styles/globals.css
Labels: enhancement

#121 implement mailchimp shayan
  client/package-lock.json
  client/package.json
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
Labels: enhancement

#117 54-implement-design-on-gallery-shayan
  client/src/pages/AboutPage/AboutPage.css
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ErrorPage/ErrorPage.css
  client/src/pages/EventsPage/EventsPage.css
  client/src/pages/GalleryPage/GalleryPage.css
  client/src/pages/GalleryPage/GalleryPage.jsx
  client/src/pages/GalleryPage/components/GalleryCard/GalleryCard.css
  client/src/pages/GalleryPage/components/GalleryCard/GalleryCard.jsx
  client/src/pages/GetInvolvedPage/GetInvolvedPage.css
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.css
  client/src/pages/HomePage/components/HomeHero/HomeHero.css
  client/src/pages/HomePage/components/HomeHero/HomeHero.jsx
  client/src/pages/HomePage/components/HomeServicesSection/HomeServicesSection.css
  client/src/pages/LoadingPage/LoadingPage.css
  client/src/pages/NewsPage/NewsPage.css
  client/src/pages/NotFoundPage/NotFoundPage.css
  client/src/pages/ServicesPage/ServicesPage.css
  client/src/styles/globals.css
Labels: enhancement

#78 48-create a button back to the top for mobile version-khadija
  client/package-lock.json
  client/package.json
  client/src/components/ScrollToTop/ScrollToTopButton.css
  client/src/components/ScrollToTop/ScrollToTopButton.jsx
  client/src/layouts/RootLayout/RootLayout.jsx
  package-lock.json
Labels: enhancement

#140 fix the bug
  client/vercel.json
Labels: bug, enhancement

#148 fix web3form for get involve
  client/src/pages/ContactUsPage/components/ContactUsForm/ContactUsForm.jsx
  client/src/pages/GetInvolvedPage/components/VolunteerForm/VolunteerForm.css
  client/src/pages/GetInvolvedPage/components/VolunteerForm/VolunteerForm.jsx
Labels: enhancement

#159 158 - Home Page Subheading Links - Baz
  client/src/pages/HomePage/HomePage.css
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.css
  client/src/pages/HomePage/components/HomeEventsSection/HomeEventsSection.jsx
  client/src/pages/HomePage/components/HomeGetInvolvedSection/HomeGetInvolvedSection.css
  client/src/pages/HomePage/components/HomeGetInvolvedSection/HomeGetInvolvedSection.jsx
  client/src/pages/HomePage/components/HomeHero/HomeHero.css
  client/src/pages/HomePage/components/HomeNewsSection/HomeNewsSection.css
  client/src/pages/HomePage/components/HomeNewsSection/HomeNewsSection.jsx
  client/src/pages/HomePage/components/HomeServicesSection/HomeServicesSection.css
  client/src/pages/HomePage/components/HomeServicesSection/HomeServicesSection.jsx
  client/src/styles/globals.css
Labels: enhancement
